

name: Build and Deploy to Docker hub

on:
  push:
    branches:
      - master

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
    - name: check out app
      uses: actions/checkout@v2

    - name: Log in to Docker hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}       

    - name: Build and Push Docker image
      uses: docker/build-push-actions@v2
      with:
        context: .
        file: ./docker/Dockerfile.user
        push: true
        tags: dufferdeepu/week-18-class

    - name: verify pushed image
      run: docker pull dufferdeepu/week-18-class:latest

